server.port = 8090
#WMS database
wms.datasource.jdbc-url=jdbc:oracle:thin:@//10.86.231.50:1521/PROD
wms.datasource.username=k1706kw
wms.datasource.password=atis0815
wms.datasource.driver-class-name=oracle.jdbc.OracleDriver
wms..datasource.hikari.connection-timeout = 600000
wms.datasource.hikari.maximum-pool-size = 15
wms.datasource.hikari.max-lifetime=1800000

#WCS database
wcs.datasource.jdbc-url=jdbc:oracle:thin:@//10.86.231.20:1521/PROD
wcs.datasource.username=k1706kc
wcs.datasource.password=atis0815
wcs.datasource.driver-class-name=oracle.jdbc.OracleDriver
wcs..datasource.hikari.connection-timeout = 600000
wcs.datasource.hikari.maximum-pool-size = 15
wcs.datasource.hikari.max-lifetime=1800000


#WCS-H database
wcsh.datasource.jdbc-url=jdbc:oracle:thin:@//10.86.231.20:1521/PROD
wcsh.datasource.username=K1706KCH
wcsh.datasource.password=atis0815
wcsh.datasource.driver-class-name=oracle.jdbc.OracleDriver
wcsh..datasource.hikari.connection-timeout = 600000
wcsh.datasource.hikari.maximum-pool-size = 15
wcsh.datasource.hikari.max-lifetime=1800000

#SRC database
src.datasource.jdbc-url=jdbc:oracle:thin:@//10.86.231.46:1521/SVCOSR
src.datasource.username=osr
src.datasource.password=syslog
src.datasource.driver-class-name=oracle.jdbc.OracleDriver
src..datasource.hikari.connection-timeout = 600000
src.datasource.hikari.maximum-pool-size = 15
src.datasource.hikari.max-lifetime=1800000