server.port = 8090
#Database1
db1.datasource.jdbc-url={DB1_URL}
db1.datasource.username={DB1_USERNAME}
db1.datasource.password={DB1_PASSWORD}
db1.datasource.driver-class-name=oracle.jdbc.OracleDriver
db1.datasource.hikari.connection-timeout = 600000
db1.datasource.hikari.maximum-pool-size = 15
db1.datasource.hikari.max-lifetime=1800000

#Database2
db2.datasource.jdbc-url={DB2_URL}
db2.datasource.username={DB2_USERNAME}
db2.datasource.password={DB2_PASSWORD}
db2.datasource.driver-class-name=oracle.jdbc.OracleDriver
db2.datasource.hikari.connection-timeout = 600000
db2.datasource.hikari.maximum-pool-size = 15
db2.datasource.hikari.max-lifetime=1800000


#Databse3
db3.datasource.jdbc-url={DB3_URL}
db3.datasource.username={DB3_USERNAME}
db3.datasource.password={DB3_PASSWORD}
db3.datasource.driver-class-name=oracle.jdbc.OracleDriver
db3.datasource.hikari.connection-timeout = 600000
db3.datasource.hikari.maximum-pool-size = 15
db3.datasource.hikari.max-lifetime=1800000

#Database4
db4.datasource.jdbc-url={DB4_URL}
db4.datasource.username={DB4_USERNAME}
db4.datasource.password={DB4_PASSWORD}
db4.datasource.driver-class-name=oracle.jdbc.OracleDriver
db4.datasource.hikari.connection-timeout = 600000
db4.datasource.hikari.maximum-pool-size = 15
db4.datasource.hikari.max-lifetime=1800000